stages:
  - test
  - deploy

test-code-job:
  stage: test
  script:
    - pytest

deploy-code-job:
  stage: deploy
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - pip install -r requirements.txt
    - export PORT=5000
    - gunicorn --config gunicorn_config.py wsgi:app

  