stages:
  - test
  - deploy

test-code-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python3 -m pytest

deploy-code-job:
  stage: deploy
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - export PORT=5000
    - gunicorn --config gunicorn_config.py wsgi:app

deploy-code-job1:
  stage: deploy
  script:
    - dpl --provider=heroku --app=jd22@ic.ac.uk-simplewebapp1 --api-key=97f2319f-2aa2-47d1-87a9-1935d1b4a2a3



  