stages:
  - test
  - build
  - deploy

test-code-job:
  stage: test
  script:
    - pip install -r requirements.txt
    - python3 -m pytest

build-code-job:
  stage: build
  script:
    - python3 -m venv venv
    - . venv/bin/activate
    - export PORT=5000
    - (gunicorn --config gunicorn_config.py wsgi:app --bind 0.0.0.0:5000 > log.txt 2 > log.txt &)

deploy-code-job:
  stage: deploy
  script:
    - dpl --provider=heroku --app=simplewebapp1 --api-key=396bb04a-af67-46d7-a21f-e016b4df537a



  